import { AsyncPipe } from '@angular/common'; import { Component, inject } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { TranslatorRepository } from '../repositories/translator.repository'; import { Translator } from '../models/patch.models'; import { AuthService } from '../services/auth.service'; import { StatusMessageService } from '../shared/status-message.service'; import { Router } from '@angular/router';
@Component({ selector:'app-admin-translators-page', standalone:true, imports:[AsyncPipe, FormsModule], templateUrl:'./admin-translators-page.component.html', styleUrl:'./admin-master-page.component.css' })
export class AdminTranslatorsPageComponent {
 private readonly repo=inject(TranslatorRepository); private readonly status=inject(StatusMessageService); private readonly auth=inject(AuthService); private readonly router=inject(Router);
 protected readonly items=this.repo.watchAll(); protected open=false; protected id:string|null=null; protected shortName=''; protected name=''; protected link='';
 protected add():void { this.id=null; this.shortName=''; this.name=''; this.link=''; this.open=true; } protected edit(x:Translator):void { this.id=x.id; this.shortName=x.shortName; this.name=x.name; this.link=x.link??''; this.open=true; } protected close():void { this.open=false; }
 protected async save():Promise<void> { if(!this.shortName.trim()||!this.name.trim()){this.status.show('กรุณาระบุชื่อย่อและชื่อเต็มของทีมแปล','error');return;} try { const editing=!!this.id; if(this.id) await this.repo.update(this.id,this.shortName,this.name,this.link); else await this.repo.create(this.shortName,this.name,this.link); this.close(); this.status.show(editing?'แก้ไขทีมแปลสำเร็จ':'เพิ่มทีมแปลสำเร็จ'); } catch(e){this.status.show(e instanceof Error?e.message:'ไม่สามารถบันทึกทีมแปลได้','error');} }
 protected async remove(x:Translator):Promise<void>{if(!window.confirm(`ยืนยันการลบ ${x.shortName} — ${x.name} หรือไม่?`))return;try{await this.repo.delete(x.id);this.status.show('ลบทีมแปลสำเร็จ');}catch(e){this.status.show(e instanceof Error?e.message:'ไม่สามารถลบทีมแปลได้','error');}} protected async signOut():Promise<void>{await this.auth.signOut();await this.router.navigateByUrl('/',{replaceUrl:true});}
}
