import { AsyncPipe } from '@angular/common'; import { Component, DestroyRef, inject } from '@angular/core'; import { FormsModule } from '@angular/forms'; import { ActivatedRoute, Router } from '@angular/router'; import { takeUntilDestroyed } from '@angular/core/rxjs-interop'; import { take } from 'rxjs'; import { TranslatorRepository } from '../repositories/translator.repository'; import { Translator } from '../models/patch.models'; import { AuthService } from '../services/auth.service'; import { StatusMessageService } from '../shared/status-message.service'; import { AdminMasterPageComponent } from './admin-master-page.component';
@Component({ selector:'app-admin-translators-page', standalone:true, imports:[AsyncPipe, FormsModule, AdminMasterPageComponent], templateUrl:'./admin-translators-page.component.html' })
export class AdminTranslatorsPageComponent {
 private readonly repo=inject(TranslatorRepository); private readonly status=inject(StatusMessageService); private readonly auth=inject(AuthService); private readonly router=inject(Router); private readonly route=inject(ActivatedRoute); private readonly destroyRef=inject(DestroyRef); private appliedQueryId:string|null=null;
 protected readonly items=this.repo.watchAll(); protected open=false; protected id:string|null=null; protected shortName=''; protected name=''; protected modTool=''; protected link='';
 constructor() { this.route.queryParamMap.pipe(takeUntilDestroyed(this.destroyRef)).subscribe((params) => { const queryId=params.get('edit'); if (!queryId || queryId===this.appliedQueryId) return; this.items.pipe(take(1)).subscribe((items) => { const translator=items.find((item) => item.id===queryId); if (translator) { this.appliedQueryId=queryId; this.edit(translator); } }); }); }
 private clearEditQuery():void { if (this.route.snapshot.queryParamMap.has('edit')) void this.router.navigate([], { relativeTo:this.route, queryParams:{ edit:null }, queryParamsHandling:'merge', replaceUrl:true }); }
 protected add():void { this.clearEditQuery(); this.id=null; this.shortName=''; this.name=''; this.modTool=''; this.link=''; this.open=true; } protected edit(x:Translator):void { this.id=x.id; this.shortName=x.shortName; this.name=x.name; this.modTool=x.modTool??''; this.link=x.link??''; this.open=true; } protected close():void { this.open=false; this.clearEditQuery(); }
 protected async save():Promise<void> { if(!this.shortName.trim()||!this.name.trim()){this.status.show('กรุณาระบุชื่อย่อและชื่อเต็มของทีมแปล','error');return;} try { const editing=!!this.id; if(this.id) await this.repo.update(this.id,this.shortName,this.name,this.link,this.modTool); else await this.repo.create(this.shortName,this.name,this.link,this.modTool); this.close(); this.status.show(editing?'แก้ไขทีมแปลสำเร็จ':'เพิ่มทีมแปลสำเร็จ'); } catch(e){this.status.show(e instanceof Error?e.message:'ไม่สามารถบันทึกทีมแปลได้','error');} }
 protected async remove(x:Translator):Promise<void>{if(!window.confirm(`ยืนยันการลบ ${x.shortName} — ${x.name} หรือไม่?`))return;try{await this.repo.delete(x.id);this.status.show('ลบทีมแปลสำเร็จ');}catch(e){this.status.show(e instanceof Error?e.message:'ไม่สามารถลบทีมแปลได้','error');}} protected async signOut():Promise<void>{await this.auth.signOut();await this.router.navigateByUrl('/',{replaceUrl:true});}
}
